{% set name = "azure-mgmt-msi" %}
{% set version = "7.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 8622bc9a164169a0113728ebe7fd43a88189708ce6e10d4507247d6907987167

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - isodate >=0.6.1
    - typing-extensions>=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.5.0

test:
  imports:
    - azure.mgmt.msi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure MSI Management Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Microsoft Azure MSI Management Client Library for Python
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - andreyz4k
