travis:
  secure:
    BINSTAR_TOKEN: eL2Fx+ncd2umxobWTCjD995xihdCtqJtLggg4oaySYsgI4aKdnAvUQ+cjG0xnGJgGqcOXx2WxMQBBCzuXRmu8pZgMtGjzxJ5NbFJqzklfbLdAqg7DBvVMvKOAtx19IQtPD1rCdVSaoRwClUsp3EgPlT2OT98GrsWfXbmE6dPPUZlAvqmzqvuxsHfKRnDDa55GzORSNJt06XllM+Ztm8NpwFHoEDc7X883Qg6gNy98nllsk0IU8yGg48+NXZ9GoczpaSNaMd1Njb2zMzvESmaXHEa2Zm0JvbyjmkmUf4opvDOL4myNbPiPt0wTfB6Y9PRRKzd7IdvZHmSKHa4qJDusvbTIOMNlycYvelF3B+gaereYiuDHEnMJWSr77HloMEVW4UU9t5k8yBI8DUlGELqXL3K9HHB5tsyqZDvsv6pS57SGUVasQYmpjXz0yA38iSeOfGwn6d7r4R5m7ZOWWf/YcFVLP6CCAHH7HCjW/6g8bez4Gh4VkMh70vh/Yr1DZzijUYHUGSEat4lvUzurqkOJkkvS96XBa5zdN7R6N81VrwKQqtk8HSCZMmganUxJvHrm6xtZC/nToN0n0nexPluMbSLz1m5vl91azKxmOa7Z0Oct3x9Bfq9hBdVEQs3DYxB7ubngVg71/kvv4RsTNIiLvkV51jNBWXyrM1OGm//+bQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
