travis:
  secure:
    BINSTAR_TOKEN: AbInF3k3C3rll5uueBu5TqQy/7dpFqtt/1GJmATttkKHg8aNYCLnYH316iLvGZgPRmWfJwApzrqvr22lEeJeu9UwjS1wZ8QYSEYCKEUeOimJCxVvPuUKjbhbfo4dR9iA9jr5oZzPN8BOp0yJuZtApnU2Fc+n0qk2txDHYeh9CrXbz1bPSBrmQHOQO3kHvgfjQJY0FbkKuspEJo/JNNfvnNXnCfXe3fXNwNVeowkcRu2QGUAW8POlqmXKNQzs1y77BHI4Ltg7MXwuCi6+1R4Sh8ho+qAFVxcdBL6tY+mbOqeaD5gQx5m+zA/Zk1BWTS+0tmXefEPMkymzov/CrLbYTC058c3IuVgtsi22nKcrXGIMevRqU3jtzBuuWqsip/P7yAW3yMM4xbg0u+Q4wDpQOEQZjkVGdRFjP79pqJGnX3Mxd2Iq1Ji52RVnIlXb7qjnR60JvZ9a973HK+6Ng615tDNkSjp7Q0E4QZ3qZ3Fe39mSMAWSHv9IRomgGojJkN3XTuotHg61FHvofXj6i/zoltnB8xocR2DnmwcKwd2GUqua9/LAWn/gWvj7PNwegFNbOe48oT2w8/q+tiylzdMEIVo1LMsUJO7Y7NKvZC5LX63l3tLmUlCcgOauctcrgaArFyrVoC4b5nAM2P+3cwqhlCk5L+JE1aw0LEaoSMoOWxg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
